import React, { useState } from "react";
import Link from "next/link";
import styles from "../styles/Layout.module.css";
import Head from "next/head";

function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Coffee Burmunq</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.layout_mid_section_container}>{children}</div>
      <Footer />
    </div>
  );
}

export default Layout;

const Navbar = () => {
  const [mobileNavbarActive, setmobileNavbarActive] = useState(false);

  const toggleBurger = () => {
    setmobileNavbarActive(!mobileNavbarActive);
  };

  const navbar_links = [
    {
      name: "Menu",
      link: "/menu",
    },
    {
      name: "About",
      link: "/about",
    },
  ];

  return (
    <div className={styles.navbar}>
      <div
        className={styles.navbar_logo}
        onClick={() => {
          setmobileNavbarActive(false);
        }}
      >
        <Link href="/">
          <h1>COFFEE BURMUNQ</h1>
        </Link>
      </div>
      {/*  */}
      <ul className={styles.navbar_links}>
        {navbar_links.map((link, index) => {
          return (
            <li key={index}>
              <Link href={link.link}>{link.name}</Link>
            </li>
          );
        })}
      </ul>
      {/*  */}

      <div className={styles.burger_menu} onClick={toggleBurger}>
        <span className={styles.burger_menu_line}></span>
        <span className={styles.burger_menu_line}></span>
        <span className={styles.burger_menu_line}></span>
      </div>
      <ul
        className={`${styles.navbar_links_mobile} ${
          mobileNavbarActive ? styles.navbar_links_mobile_visible : ""
        }`}
      >
        {navbar_links.map((link, index) => {
          return (
            <li key={index} onClick={toggleBurger}>
              <Link href={link.link}>{link.name}</Link>
            </li>
          );
        })}
      </ul>
    </div>
  );
};

const Footer = () => {
  return (
    <div className={styles.footer}>
      <div className={styles.footer_contact}>
        <h3>Contact Us</h3>
        <div className={styles.footer_contact_info}>
          <div className={styles.footer_contact_info_left}>
            <p>Address:</p>
            <p>City, State, Zip:</p>
            <p>Phone:</p>
          </div>
          <div className={styles.footer_contact_info_right}>
            <p>102 S Glendale Ave 1/2</p>
            <p>Glendale, CA 91205</p>
            <p>818-888-8888</p>
          </div>
        </div>
      </div>
      <div className={styles.footer_logo}>
        <h1>COFFEE BURMUNQ</h1>
      </div>
    </div>
  );
};
